import './menu-scroll.test.mjs';
import './polish.test.mjs';
import "./final-menu.test.mjs";
import './quick-cart.test.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {sanitizeCart,addLine,totals,expandCart,lineKey,normalizePhone,normalizeSearch,cleanText,formatPrice,validateCustomer,buildMessage,whatsappUrl,makeReference} from '../src/lib/core.mjs';
const menu=JSON.parse(readFileSync(new URL('../src/data/menu.json',import.meta.url),'utf8'));
const P=menu.products;const dolma=P.find(p=>p.name==='دولمة');const pasta=P.find(p=>p.name.startsWith('معكرونة'));
const customer={name:'زبون اختبار',phone:'07700000000',city:'بغداد',address:'عنوان تجريبي واضح',note:''};
test('All 73 source price options, 58 products, eight categories',()=>{assert.equal(P.reduce((n,p)=>n+p.variants.length,0),73);assert.equal(P.length,58);assert.equal(menu.categories.length,8);assert.equal(new Set(P.map(p=>p.id)).size,P.length);assert.equal(new Set(P.flatMap(p=>p.variants.map(v=>v.id))).size,73);});
test('Every variant has a positive integer IQD price and original row',()=>{for(const p of P)for(const v of p.variants){assert.ok(Number.isInteger(v.price)&&v.price>0);assert.ok(v.sourceRow>=2&&v.sourceRow<=74);}});
test('Catalog asset references resolve',()=>{for(const p of P){assert.doesNotThrow(()=>readFileSync(new URL('../public'+p.image,import.meta.url)));}});
test('Create line and calculate integer subtotal',()=>{const cart=addLine([],dolma,dolma.variants[0].id,2);assert.deepEqual(totals(cart,P),{count:2,subtotal:36000});});
test('Adding the same selection merges quantities',()=>{let c=addLine([],dolma,dolma.variants[0].id,2);c=addLine(c,dolma,dolma.variants[0].id,1);assert.equal(c.length,1);assert.equal(c[0].quantity,3);});
test('Distinct sizes stay on separate lines',()=>{let c=addLine([],dolma,dolma.variants[0].id,1);c=addLine(c,dolma,dolma.variants[1].id,1);assert.equal(c.length,2);assert.equal(totals(c,P).subtotal,44000);});
test('Different notes stay separate',()=>{let c=addLine([],dolma,dolma.variants[0].id,1,'','ملاحظة 1');c=addLine(c,dolma,dolma.variants[0].id,1,'','ملاحظة 2');assert.equal(c.length,2);});
test('Pasta has explicit meat/chicken options at source price',()=>{assert.deepEqual(pasta.choices,['لحم','دجاج']);assert.equal(pasta.variants[0].price,15000);assert.equal(pasta.variants[0].label,'عائلي');let c=addLine([],pasta,pasta.variants[0].id,1,'لحم');c=addLine(c,pasta,pasta.variants[0].id,1,'دجاج');assert.equal(c.length,2);assert.equal(totals(c,P).subtotal,30000);});
test('Reject invalid product options and quantities',()=>{assert.deepEqual(addLine([],dolma,'bad',1),[]);for(const q of [-1,0,1.5,NaN,100])assert.deepEqual(addLine([],dolma,dolma.variants[0].id,q),[]);assert.deepEqual(addLine([],pasta,pasta.variants[0].id,1,'غير موجود'),[]);});
test('Sanitization rejects stale ids and tampered prices',()=>{let c=addLine([],dolma,dolma.variants[0].id,1);c[0].price=1;const restored=sanitizeCart([...c,{productId:'removed',variantId:'gone',quantity:5}],P);assert.equal(restored.length,1);assert.equal(totals(restored,P).subtotal,18000);assert.equal(restored[0].price,undefined);});
test('Sanitization handles corrupt shapes',()=>{for(const v of [null,{},false,'bad',1])assert.deepEqual(sanitizeCart(v,P),[]);assert.deepEqual(sanitizeCart([null,{},false,'bad'],P),[]);});
test('Sanitization bounds quantity and merges duplicate stored keys',()=>{const c=addLine([],dolma,dolma.variants[0].id,1);const r=sanitizeCart([{...c[0],quantity:60},{...c[0],quantity:65}],P);assert.equal(r.length,1);assert.equal(r[0].quantity,99);});
test('Normalize Iraqi mobile numbers including Arabic and Persian digits',()=>{for(const p of ['07700000000','+9647700000000','00964 770 000 0000','٧٧٠٠٠٠٠٠٠٠','۰۷۷۰۰۰۰۰۰۰۰'])assert.equal(normalizePhone(p),'9647700000000');});
test('Reject invalid mobile numbers',()=>{for(const p of ['','abc','077','0770000000000','00964770000000x','١٢٣٤','12345678901'])assert.equal(normalizePhone(p),'');});
test('Arabic search normalizes hamza, diacritics, tatweel and Persian forms',()=>{assert.equal(normalizeSearch('أَطْبَاق الـرُّز'),'اطباق الرز');assert.equal(normalizeSearch('کبة حلب'),normalizeSearch('كبه حلب'));assert.equal(normalizeSearch('١٠ قطع'),'10 قطع');});
test('Text removes directional override and control characters',()=>{assert.equal(cleanText('  a\u202eb\u0000  '),'ab');assert.equal(cleanText('abcdef',3),'abc');});
test('Customer required fields are validated',()=>{assert.deepEqual(validateCustomer(customer),{});assert.equal(Object.keys(validateCustomer({})).length,4);assert.ok(validateCustomer({...customer,phone:'nope'}).phone);});
test('Generated WhatsApp message contains items, data, quantity, subtotal and disclaimers',()=>{let c=addLine([],dolma,dolma.variants[0].id,2,'','طلب ضلوع');c=addLine(c,pasta,pasta.variants[0].id,1,'دجاج');const m=buildMessage(c,P,{...customer,note:'وقت التجهيز حسب الاتفاق'},'FF-TEST');for(const text of ['FF-TEST','زبون اختبار','بغداد','2 × 18,000','36,000','دجاج','51,000','طلب ضلوع','وقت التجهيز حسب الاتفاق','غير مشمولة'])assert.ok(m.includes(text),text);});
test('WhatsApp URL encoding is a lossless round trip',()=>{const m=buildMessage(addLine([],dolma,dolma.variants[0].id,1),P,customer,'FF-TEST');const u=new URL(whatsappUrl('9647737773444',m));assert.equal(u.hostname,'wa.me');assert.equal(u.pathname,'/9647737773444');assert.equal(u.searchParams.get('text'),m);});
test('Empty and invalid orders cannot be composed',()=>{assert.throws(()=>buildMessage([],P,customer,'F'),/EMPTY_CART/);assert.throws(()=>buildMessage(addLine([],dolma,dolma.variants[0].id,1),P,{...customer,phone:'bad'},'F'),/INVALID_CUSTOMER/);});
test('Reference and format are deterministic',()=>{assert.equal(makeReference(new Date('2026-09-17T12:00:00Z'),0),'FF-20260917-0000');assert.equal(formatPrice(18000),'18,000');});
test('Full 73-option cart restores and produces no NaN',()=>{let c=[];for(const p of P)for(const v of p.variants)c=addLine(c,p,v.id,1,p.choices[0]||'');const restored=sanitizeCart(JSON.parse(JSON.stringify(c)),P);assert.equal(restored.length,73);assert.ok(Number.isSafeInteger(totals(restored,P).subtotal));assert.equal(expandCart(restored,P).length,73);});

import "./enhancements.test.mjs";
